INSERT INTO region (nom_region,ville_chef) VALUES ('Alsace','Strasbourg');
INSERT INTO region (nom_region,ville_chef) VALUES ('Aquitaine','Bordeaux');
INSERT INTO region (nom_region,ville_chef) VALUES ('Auvergne','Clermont-Ferrand');
INSERT INTO region (nom_region,ville_chef) VALUES ('Basse Normandie','Caen');
INSERT INTO region (nom_region,ville_chef) VALUES ('Bourgogne','Dijon');
INSERT INTO region (nom_region,ville_chef) VALUES ('Bretagne','Rennes');
INSERT INTO region (nom_region,ville_chef) VALUES ('Centre','Orléans');
INSERT INTO region (nom_region,ville_chef) VALUES ('Champagne Ardenne','Châlons-en-Champagne');
INSERT INTO region (nom_region,ville_chef) VALUES ('Corse','Ajaccio');
INSERT INTO region (nom_region,ville_chef) VALUES ('Franche Comte','Besançon');
INSERT INTO region (nom_region,ville_chef) VALUES ('Haute Normandie','Rouen');
INSERT INTO region (nom_region,ville_chef) VALUES ('Ile de France','Paris');
INSERT INTO region (nom_region,ville_chef) VALUES ('Languedoc Roussillon','Montpellier');
INSERT INTO region (nom_region,ville_chef) VALUES ('Limousin','Limoges');
INSERT INTO region (nom_region,ville_chef) VALUES ('Lorraine','Metz');
INSERT INTO region (nom_region,ville_chef) VALUES ('Midi-Pyrénées','Toulouse');
INSERT INTO region (nom_region,ville_chef) VALUES ('Nord Pas de Calais','Lille');
INSERT INTO region (nom_region,ville_chef) VALUES ('Provence Alpes Côte d\'Azur','Marseille');
INSERT INTO region (nom_region,ville_chef) VALUES ('Pays de la Loire','Nantes');
INSERT INTO region (nom_region,ville_chef) VALUES ('Picardie','Amiens');
INSERT INTO region (nom_region,ville_chef) VALUES ('Poitou Charente','Poitiers');
INSERT INTO region (nom_region,ville_chef) VALUES ('Rhone Alpes','Lyon');