INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('01', 22, 'Ain');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('02', 20, 'Aisne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('03', 3, 'Allier');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('04', 18, 'Alpes de haute provence');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('05', 18, 'Hautes alpes');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('06', 18, 'Alpes maritimes');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('07', 22, 'Ardèche');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('08', 8, 'Ardennes');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('09', 16, 'Ariège');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('10', 8, 'Aube');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('11', 13, 'Aude');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('12', 16, 'Aveyron');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('13', 18, 'Bouches du rhône');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('14', 4, 'Calvados');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('15', 3, 'Cantal');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('16', 21, 'Charente');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('17', 21, 'Charente maritime');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('18', 7, 'Cher');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('19', 14, 'Corrèze');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('21', 5, 'Côte d\'or');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('22', 6, 'Côtes d\'Armor');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('23', 14, 'Creuse');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('24', 2, 'Dordogne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('25', 10, 'Doubs');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('26', 22, 'Drôme');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('27', 11, 'Eure');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('28', 7, 'Eure et Loir');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('29', 6, 'Finistère');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('30', 13, 'Gard');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('31', 16, 'Haute garonne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('32', 16, 'Gers');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('33', 2, 'Gironde');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('34', 13, 'Hérault');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('35', 6, 'Ile et Vilaine');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('36', 7, 'Indre');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('37', 7, 'Indre et Loire');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('38', 22, 'Isère');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('39', 10, 'Jura');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('40', 2, 'Landes');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('41', 7, 'Loir et Cher');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('42', 22, 'Loire');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('43', 3, 'Haute Loire');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('44', 19, 'Loire Atlantique');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('45', 7, 'Loiret');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('46', 16, 'Lot');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('47', 2, 'Lot et Garonne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('48', 13, 'Lozère');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('49', 19, 'Maine et Loire');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('50', 4, 'Manche');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('51', 8, 'Marne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('52', 8, 'Haute Marne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('53', 19, 'Mayenne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('54', 15, 'Meurthe et Moselle');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('55', 15, 'Meuse');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('56', 6, 'Morbihan');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('57', 15, 'Moselle');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('58', 5, 'Nièvre');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('59', 17, 'Nord');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('60', 20, 'Oise');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('61', 4, 'Orne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('62', 17, 'Pas de Calais');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('63', 3, 'Puy de Dôme');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('64', 2, 'Pyrénées Atlantiques');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('65', 16, 'Hautes Pyrénées');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('66', 13, 'Pyrénées Orientales');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('67', 1, 'Bas Rhin');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('68', 1, 'Haut Rhin');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('69', 22, 'Rhône');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('70', 10, 'Haute Saône');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('71', 5, 'Saône et Loire');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('72', 19, 'Sarthe');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('73', 22, 'Savoie');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('74', 22, 'Haute Savoie');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('75', 12, 'Paris');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('76', 11, 'Seine Maritime');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('77', 12, 'Seine et Marne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('78', 12, 'Yvelines');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('79', 21, 'Deux Sèvres');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('80', 20, 'Somme');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('81', 16, 'Tarn');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('82', 16, 'Tarn et Garonne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('83', 18, 'Var');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('84', 18, 'Vaucluse');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('85', 19, 'Vendée');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('86', 21, 'Vienne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('87', 14, 'Haute Vienne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('88', 15, 'Vosges');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('89', 5, 'Yonne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('90', 10, 'Territoire de Belfort');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('91', 12, 'Essonne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('92', 12, 'Hauts de Seine');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('93', 12, 'Seine Saint Denis');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('94', 12, 'Val de Marne');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('95', 12, 'Val d\'Oise');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('2A', 9, 'Corse du Sud');
INSERT INTO departement (code_departement,id_region,nom_departement) VALUES ('2B', 9, 'Haute Corse');